language: php

php:
  - 7.2

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
  fast_finish: true

cache:
  directories:
    - vendor

install:
  - composer update --no-interaction

script:
- vendor/bin/phpunit
